apiVersion: v1
kind: ConfigMap
metadata:
  name: caddy-config
data:
  Caddyfile: |
    llm1.rack.co {
        reverse_proxy rack-service:3939
        tls {
            issuer acme
        }
    }

    :8080 {
        reverse_proxy rack-service:3939
    }
